### ISSUE TITLE
Install Error from Composer

### ISSUE THREAD

**Issue by shuaiZend** [emizentech/magento2-custom-smtp#2]
```
[InvalidArgumentException]                                                                                
  Could not find package emizentech/customsmtp at any version for your minimum-stability (dev). Check the   
  package spelling or your minimum-stability 
```

**Comment by bangerkuwranger** [comment]
You need to set your minimum stability in the composer.json file at the root of your magento install to 'dev'. See here for more info on the risks of doing so: http://webtips.krajee.com/setting-composer-minimum-stability-application/

**Comment by emizentech** [comment]
resolved in latest commits
