### ISSUE TITLE
Send Mail not Working

### ISSUE THREAD

**Issue by Git-Rajkumar** [emizentech/magento2-custom-smtp#3]
Hello emizen,

I installed manually your cutom-smtp module in locally.  and I follow your readme documents 
When I compile your Custom-Smtp Module ,  I got Some Errors see this link https://imagebin.ca/2bG6U6y0DdOg/EmizenCustomSMTP.png 

then, After Compile then go to Admin panel , i got your Extension. Setup Smtp Configuration and send a mail , but send mail is not working?. But Testing Send mail is Working.

How to Fix this problem?,   Why send mail is Not working? , and Why Show This Error While I Compile your Module?. Thanks in advance....

**Comment by lgjackhuang** [comment]
Same here.. i got that exception too.

**Comment by Chibizzle** [comment]
Same here...

**Comment by filipp-k** [comment]
That was fixed with PR #9. Pleas update vendors
